source 'https://rubygems.org'

gem 'rack', '~> 2.1.4'
gem 'grape', '~> 1.2.2'
gem 'grape-entity', '~> 0.5.1'
gem 'activerecord', '~> 5.0.2', require: 'active_record'
gem 'otr-activerecord', '~> 1.2.1'
gem 'sqlite3'
gem 'rake'

group :development do
  gem 'shotgun'
end

group :test do
  gem 'rack-test', require: 'rack/test'
  gem 'database_cleaner'
end
