source 'https://rubygems.org'

gem 'rack', '~> 3.0'
gem 'activerecord', '~> 7.0.1', require: 'active_record'
gem 'otr-activerecord', path: '../../'
gem 'sqlite3'
gem 'rake'

group :development do
  gem 'shotgun'
end
