require 'active_record'
require 'hashie-forbidden_attributes'
require 'otr-activerecord/version'
require 'otr-activerecord/activerecord'
require 'otr-activerecord/middleware/connection_management.rb'
require 'otr-activerecord/defaults'
